import type {
  Empresa,
  ContatoEmpresa,
  Atividade,
  OnboardingCliente,
  OnboardingTarefa,
  FechamentoMensal,
} from './types'

export const mockEmpresas: Empresa[] = [
  {
    id: '1',
    codigoEmpresa: 1001,
    razaoSocial: 'Tech Solutions Ltda',
    cnpj: '12.345.678/0001-90',
    telefonePrincipal: '(11) 98765-4321',
    responsavelPrincipal: 'João Silva',
    ativo: true,
  },
  {
    id: '2',
    codigoEmpresa: 1002,
    razaoSocial: 'Comércio ABC S.A.',
    cnpj: '23.456.789/0001-01',
    telefonePrincipal: '(11) 97654-3210',
    responsavelPrincipal: 'Maria Santos',
    ativo: true,
  },
  {
    id: '3',
    codigoEmpresa: 1003,
    razaoSocial: 'Serviços XYZ ME',
    cnpj: '34.567.890/0001-12',
    telefonePrincipal: '(11) 96543-2109',
    responsavelPrincipal: 'Pedro Costa',
    ativo: true,
  },
  {
    id: '4',
    codigoEmpresa: 1004,
    razaoSocial: 'Indústria Delta Ltda',
    cnpj: '45.678.901/0001-23',
    telefonePrincipal: '(11) 95432-1098',
    responsavelPrincipal: 'Ana Oliveira',
    ativo: true,
  },
  {
    id: '5',
    codigoEmpresa: 1005,
    razaoSocial: 'Consultoria Omega',
    cnpj: '56.789.012/0001-34',
    telefonePrincipal: '(11) 94321-0987',
    responsavelPrincipal: 'Carlos Pereira',
    ativo: true,
  },
]

export const mockContatos: ContatoEmpresa[] = [
  {
    id: '1',
    empresaId: '1',
    nome: 'João Silva',
    telefone: '(11) 98765-4321',
    email: 'joao@techsolutions.com',
    tipoContato: 'DP',
  },
  {
    id: '2',
    empresaId: '1',
    nome: 'Paula Martins',
    telefone: '(11) 98765-4322',
    email: 'paula@techsolutions.com',
    tipoContato: 'FINANCEIRO',
  },
  {
    id: '3',
    empresaId: '2',
    nome: 'Maria Santos',
    telefone: '(11) 97654-3210',
    email: 'maria@comercioabc.com',
    tipoContato: 'DP',
  },
]

export const mockAtividades: Atividade[] = [
  {
    id: '1',
    empresaId: '1',
    tipoAtividade: 'COBRANCA_PONTO_FISCAL',
    status: 'FEITO',
    diaRecorrente: 25,
    dataInicio: new Date(2025, 0, 10),
    dataExecucao: new Date(2025, 0, 25),
    responsavelInterno: 'Carla Mendes',
    telefoneUsado: '(11) 98765-4321',
    observacao: 'Enviado completo',
    prioridade: 'MEDIA',
  },
  {
    id: '2',
    empresaId: '1',
    tipoAtividade: 'COBRANCA_DOCUMENTO_FISCAL',
    status: 'PENDENTE_CLIENTE',
    diaRecorrente: 15,
    dataInicio: new Date(2025, 0, 1),
    dataExecucao: new Date(2025, 0, 15),
    responsavelInterno: 'Carla Mendes',
    telefoneUsado: '(11) 98765-4321',
    observacao: 'Aguardando documentação',
    prioridade: 'ALTA',
  },
  {
    id: '3',
    empresaId: '2',
    tipoAtividade: 'ENVIO_GUIAS_FISCAL',
    status: 'FEITO',
    diaRecorrente: 20,
    dataExecucao: new Date(2025, 0, 20),
    responsavelInterno: 'Roberto Lima',
    observacao: 'Guias enviadas',
    prioridade: 'MEDIA',
  },
  {
    id: '4',
    empresaId: '2',
    tipoAtividade: 'ENVIO_DOCUMENTOS_CONTABIL',
    status: 'EM_ANDAMENTO',
    responsavelInterno: 'Carla Mendes',
    observacao: 'Processando documentação',
    prioridade: 'ALTA',
  },
  {
    id: '5',
    empresaId: '3',
    tipoAtividade: 'COBRANCA_RECIBO_ALUGUEL',
    status: 'ATRASADO',
    diaRecorrente: 5,
    dataInicio: new Date(2025, 0, 1),
    responsavelInterno: 'Roberto Lima',
    telefoneUsado: '(11) 96543-2109',
    observacao: 'Não respondeu ao contato',
    prioridade: 'CRITICA',
  },
  {
    id: '6',
    empresaId: '3',
    tipoAtividade: 'COBRANCA_FATURAMENTO',
    status: 'PENDENTE_CLIENTE',
    responsavelInterno: 'Carla Mendes',
    observacao: 'Aguardando faturamento',
    prioridade: 'MEDIA',
  },
  {
    id: '7',
    empresaId: '4',
    tipoAtividade: 'ENVIO_GUIAS_CONTABIL',
    status: 'FEITO',
    diaRecorrente: 28,
    dataExecucao: new Date(2025, 0, 28),
    responsavelInterno: 'Fernanda Alves',
    observacao: 'Guias contábeis enviadas',
    prioridade: 'MEDIA',
  },
  {
    id: '8',
    empresaId: '5',
    tipoAtividade: 'ENVIO_DOCUMENTOS_CONTABIL',
    status: 'FEITO',
    dataExecucao: new Date(2025, 0, 22),
    responsavelInterno: 'Fernanda Alves',
    observacao: 'Documentação enviada',
    prioridade: 'MEDIA',
  },
]

export const mockOnboardings: OnboardingCliente[] = [
  {
    id: '1',
    empresaId: '5',
    dataEntrada: new Date(2025, 0, 10),
    responsavelInterno: 'Fernanda Alves',
    status: 'EM_ANDAMENTO',
  },
  {
    id: '2',
    empresaId: '1',
    dataEntrada: new Date(2024, 11, 1),
    responsavelInterno: 'Fernanda Alves',
    status: 'FEITO',
  },
]

export const mockTarefasOnboarding: OnboardingTarefa[] = [
  {
    id: '1',
    onboardingId: '1',
    tituloTarefa: 'Coletar documentos societários',
    descricaoOpcional: 'Contrato social, alterações e documentos dos sócios',
    prazo: new Date(2025, 0, 15),
    statusTarefa: 'CONCLUIDA',
    tipoTarefa: 'DOCUMENTO',
  },
  {
    id: '2',
    onboardingId: '1',
    tituloTarefa: 'Cadastrar no sistema de folha',
    descricaoOpcional: 'Cadastro completo no sistema Domínio',
    prazo: new Date(2025, 0, 20),
    statusTarefa: 'EM_ANDAMENTO',
    tipoTarefa: 'CADASTRO',
  },
  {
    id: '3',
    onboardingId: '1',
    tituloTarefa: 'Configurar certificado digital',
    prazo: new Date(2025, 0, 25),
    statusTarefa: 'ABERTA',
    tipoTarefa: 'CONFIGURACAO_SISTEMA',
  },
]

export const mockFechamentos: FechamentoMensal[] = [
  {
    id: '1',
    empresaId: '1',
    mes: 0,
    ano: 2025,
    statusPrimeiroFechamento: 'FEITO',
    statusSegundoFechamento: 'EM_ANDAMENTO',
    statusTerceiroFechamento: 'NAO_INICIADO',
    statusProLabore: 'FEITO',
    observacao: 'Em dia',
  },
  {
    id: '2',
    empresaId: '2',
    mes: 0,
    ano: 2025,
    statusPrimeiroFechamento: 'FEITO',
    statusSegundoFechamento: 'PENDENTE_CLIENTE',
    statusTerceiroFechamento: 'NAO_INICIADO',
    statusProLabore: 'PENDENTE_CLIENTE',
    observacao: 'Aguardando documentação adicional',
  },
  {
    id: '3',
    empresaId: '3',
    mes: 0,
    ano: 2025,
    statusPrimeiroFechamento: 'EM_ANDAMENTO',
    statusSegundoFechamento: 'NAO_INICIADO',
    statusTerceiroFechamento: 'NAO_INICIADO',
    statusProLabore: 'NAO_INICIADO',
  },
]
